### ISSUE TITLE
Include "Reference Vulnerabilities" in the vulnerability details

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/reportgen#12]
There are cases where a vulnerability has a "reference vulnerabilities". 
In the UI it looks like this:
![image](https://user-images.githubusercontent.com/3126261/80284163-72ee9700-8725-11ea-9bf9-a2aa770b361c.png)

Please add this table to the vulnerability details.
To get this data, you should call the "/vulnerabilities" REST API and in the result look at:
"results[].referenced_vulnerabilities[]" field.
You should create a table with the "results[].referenced_vulnerabilities[].name" and "results[].referenced_vulnerabilities[].aqua_severity" fields.

The "Referenced Vulnerability" should be added right after the "Vulnerability Description" field.
If should have font size of 12, and should be written "REFERENCE VULNERABILITIES" .
You should not add this section if there are no referenced vulnerabilities.

The table itself should look like this (font perspective):

![image](https://user-images.githubusercontent.com/3126261/80284253-18096f80-8726-11ea-92b8-1652410e59aa.png)

If you want an example of a vulnerability with "referenced vulnerabilities" then you can scan "centos:6.10" image and look at the "critical" vulnerability (there is only one critical vulnerability).

**Comment by afdesk** [comment]
@jerbia I added 'Referenced Vulnerability' block. pushed.
but I need more details about text color.

**Comment by jerbia** [comment]
Looks good!

Can you change the font of "reference vulnerabilities" to be exactly like the "Vulnerability Description" font? Also change it to "Referenced" instead of "Reference"

![image](https://user-images.githubusercontent.com/3126261/80638366-fe8b5f00-8a68-11ea-97f8-b6f65a3a03a8.png)

**Comment by afdesk** [comment]
Changed. pushed.
