### ISSUE TITLE
Support generating PDF of host vulnerabilities

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/reportgen#13]
Host vulnerabilities are similar to image vulnerabilities. The REST API is slightly different.

First we need to change the usage, where you can specify:
./main [-image <image name> | -host <host name>] ...

If -image -> do the PDF generation for image name (like today).
If -host -> new flow for PDF generation to host name.

What is the flow?

1. User will supply host name. 
You will get the host information by calling "/api/v2/infrastructure/node/host_name

This will give you the:
node_id (you will need this to the next REST API)
security_issues.crit_vulns
security_issues.high_vulns
security_issues.med_vulns
security_issues.low_vulns
security_issues.neg_vulns
security_issues.malware,
security_issues.last_vuln_scan (this is the scan date)
created_date (creation date)

2. To get the assurance checks:
/api/v2/status/host/node_id

Parse the "assurance_results" field, like you do for Images.

3. To get malware:
/api/v1/hosts/node_id/malware

The result is like image malware

4. To get the vulnerabilities:
/api/v1/hosts/node_id/vulnerabilities?include_vpatch_info=true&page=1&pagesize=200&skip_count=true&hide_base_image=false&node_id=<node id>

This is the detailed list of vulnerabilities. You should part is like you do for images.

5. To get the bench results:
/api/v2/risks/bench/node_id/bench_results

You will get following fields:
- cis
- kube-bench
- linux
- openshift

-- Each field will have "result.tests"
--- Each test has a "desc", "info", "pass", "warn" and "fail" and "results".
---- Each result has: "status", "test_desc", "test_info", "test_number",  "actual_value", "expected_result" 

![image](https://user-images.githubusercontent.com/3126261/80318277-be7e6f00-8811-11ea-9e82-6d2c9ee6e7e2.png)

**Comment by afdesk** [comment]
@jerbia 
can you give me samples API requests for a host report?

**Comment by jerbia** [comment]
Yes, you can use node "Default.devAJcos14b377-vm0":

https://server_name/api/v2/infrastructure/node/Default.devAJcos14b377-vm0

**Comment by afdesk** [comment]
@jerbia I added -host param, and changed rendering.
I need your decision about summary block.
Which content CLI has to add to this part?

the bench results will be later (tomorrow).

**Comment by afdesk** [comment]
And I would like more host samples for test. )

**Comment by afdesk** [comment]
@jerbia I pushed new version for review in issue-13 branch.
 
There are a few important moments for comment:
1. Font of titles (CIS, Linux...) 
2. I tested only for `-host "Default.devAJcos14b377-vm0"`. I need more samples. How can I look their?

**Comment by afdesk** [comment]
@jerbia I pushed the changes and created PR.
