### ISSUE TITLE
Replace terms "blacklist" & "whitelist"

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/reportgen#16]
We need to update this language that's used in the generated report. It should match whatever terms we change to in the Aqua commercial product.

**Comment by tbal999** [comment]
Hi do you mean this section:

**Row 41 in reportgen/pdfrender/common.go** 

var imageAssurance = map[string]string {
	"blacklisted_packages": "Blacklisted Packages",
	"custom_checks":        "Custom Checks",
	"cve_blacklist":        "Blacklisted CVE",
	"force_microenforcer":  "MicroEnforcer Deployed",
	"license":              "Approved Licenses",
	"malware":              "Malware",
	"max_score":            "Maximum Vulnerability Score",
	"max_severity":         "Maximum Vulnerability Severity",
	"partial_results":      "Partial Scan Results",
	"required_packages":    "Required Packages",
	"root_user":            "Run as Superuser",
	"sensitive_data":       "Sensitive Data",
	"trusted_base_images":  "Trusted Base Image",
	"whitelisted_licenses": "Whitelisted Licenses",
}

**Comment by afdesk** [comment]
@tbal999 thanks for your `signposting` #17 .
I saw it and changed terms. 

@tbal999 could you tell me the image with these fields? thanks!
