### ISSUE TITLE
Not getting report - possibly due to x509 certificate

### ISSUE THREAD

**Issue by mdconner** [aquasecurity/reportgen#18]
I was able to get the image to build by adding 'RUN git config --global http.sslVerify "false" ' after 'RUN apk add' in Dockerfile.

I get the following when running:  ' docker run -i -v /tmp:/reports aqua-reports -server https://aqua-tst.us.lmco.com -user <user> -password <PWD> -image cis-devsecops/static-code-scanner:beta -registry https://registry.us.lmco.com -output /reports/report.pdf'

Getting data from https://aqua-tst.us.lmco.com/api/v2/images/https://registry.us.lmco.com/cis-devsecops/static-code-scanner/beta/malware
Getting data from https://aqua-tst.us.lmco.com/api/v2/images/https://registry.us.lmco.com/cis-devsecops/static-code-scanner/beta/scan_history?order_by=-date&page=1&page_size=10
Getting data from https://aqua-tst.us.lmco.com/api/v2/images/https://registry.us.lmco.com/cis-devsecops/static-code-scanner/beta/vulnerabilities?pagesize=100&page=1
Getting data from https://aqua-tst.us.lmco.com/api/v2/images/https://registry.us.lmco.com/cis-devsecops/static-code-scanner/beta
Getting data from https://aqua-tst.us.lmco.com/api/v2/images/https://registry.us.lmco.com/cis-devsecops/static-code-scanner/beta/sensitive
2020/06/23 19:56:00 Get "https://aqua-tst.us.lmco.com/api/v2/images/https://registry.us.lmco.com/cis-devsecops/static-code-scanner/beta/sensitive": x509: certificate signed by unknown authority

I am running on a Windows 10 client with Docker Desktop and Git Bash.

Any ideas?

**Comment by jerbia** [comment]
@mdconner can you check the same against a Docker Hub image?
I have a suspicious that the registry name (https://registry.us.lmco.com) might be causing an issue due to the colon and slashes.
Please also make sure that you are specifying the registry name as defined in Aqua console (and not the registry URL).

**Comment by bunyaminoner** [comment]
I had the same issue and passed by modifying rest/requests.go like below:

# vi rest/requests.go 
`
     24 func getData(url, user, password string) []byte  {
     25         fmt.Println("Getting data from", url)
     **26         tr := &http.Transport{
     27                 TLSClientConfig: &tls.Config{InsecureSkipVerify: true},**
     28 }
     **29         client := &http.Client{Transport: tr}**
     30         req, err := http.NewRequest("GET", url, nil)
     31         req.SetBasicAuth(user, password)
     32         resp, err := client.Do(req)
     33         if err != nil{
     34                 log.Fatal(err)
     35         }
     36 
     37         if resp.StatusCode != http.StatusOK {
     38                 fmt.Println("Wrong access to the URL: ", url)
     39                 fmt.Println("Status:", resp.Status)
     40                 os.Exit(1)
     41         }
     42 
     43         bodyText, err := ioutil.ReadAll(resp.Body)
     44         return bodyText
     45 }

`

**Comment by jerbia** [comment]
@afdesk can you add an option to skip verifying SSL? Also, need to make sure we are getting an error message if HTTPS failed.

**Comment by mdconner** [comment]
This issue can be closed - no longer using this project
