### ISSUE TITLE
Missing vulnerabilities in the PDF

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/reportgen#2]
Scan image jerbi/orders-apache:1.0
See that the vulnerability details is missing many vulnerabilities.
You need to use the pagination option in the REST API.
You need to add "?pagesize=200&page=<page number>" to the /vulnerabilities request.

You need to look at you will get "result" = null
(this is one of the fields you get from the vulnerabilities query)

So basically you need to iterate until you get "results" = null
and go over page 1, 2, 3, etc...

**Comment by afdesk** [comment]
@jerbia I want to use 'count' value from the response for calculating of pages number

**Comment by jerbia** [comment]
@afdesk I am fine with that.

**Comment by afdesk** [comment]
@jerbia I've pushed new changes and created first pull request.

**Comment by jerbia** [comment]
@afdesk I don't see any pull request. Maybe you forgot to create one?

**Comment by afdesk** [comment]
> 
> 
> @afdesk I don't see any pull request. Maybe you forgot to create one?

Created now.
probably I missed a click on second page. sorry.

**Comment by afdesk** [comment]
@jerbia 
Should we close this issue now?

**Comment by jerbia** [comment]
Fixed.
