### ISSUE TITLE
Used API endpoint seems to fail for composite image name

### ISSUE THREAD

**Issue by giuseppeingoglia** [aquasecurity/reportgen#20]
Good day.
I have an image tagged as _scaling/debian:9.2_ in a Harbor registry.
When I try to get the report running the below command:

_docker run -it -v /tmp:/reports aqua-reports -server http://192.168.0.94:7050 -user administrator -password my-pass -image scaling/debian:9.2 -registry harbor -output /reports/report.pdf_

I get the following error:

_Wrong access to the URL:  http://192.168.0.94:7050/api/v2/images/harbor/scaling/debian/9.2/scan_history?order_by=-date&page=1&page_size=10
Status: 404 Not Found_

Thank you

**Comment by jerbia** [comment]
Cannot reproduce the issue (even on the same machine it happened). Closing.
