### ISSUE TITLE
Aqua SaaS Support - Status: 401 Unauthorized

### ISSUE THREAD

**Issue by andresguisado** [aquasecurity/reportgen#25]
Hi, 

It seems Reportgen is not able to login through Aqua SaaS:

❯ **docker ru**n -it -v /tmp:/reports aqua-reports -server https://fbb4b51c46.cloud.aquasec.com/ -user andres.guisado@aquasec.com -password XXXX -image alpine:3.10 -registry "vmazurecr.azurecr.io" -output /reports/report.pdf

`
Getting data from https://fbb4b51c46.cloud.aquasec.com/api/v2/images/vmazurecr.azurecr.io/alpine/3.10/malware
Getting data from https://fbb4b51c46.cloud.aquasec.com/api/v2/images/vmazurecr.azurecr.io/alpine/3.10/vulnerabilities?pagesize=100&page=1
Getting data from https://fbb4b51c46.cloud.aquasec.com/api/v2/images/vmazurecr.azurecr.io/alpine/3.10
Getting data from https://fbb4b51c46.cloud.aquasec.com/api/v2/images/vmazurecr.azurecr.io/alpine/3.10/sensitive
Getting data from https://fbb4b51c46.cloud.aquasec.com/api/v2/images/vmazurecr.azurecr.io/alpine/3.10/scan_history?order_by=-date&page=1&page_size=10
Wrong access to the URL:  https://fbb4b51c46.cloud.aquasec.com/api/v2/images/vmazurecr.azurecr.io/alpine/3.10/sensitive
**Status: 401 Unauthorized**
`

Thanks, 
Andres

**Comment by afdesk** [comment]
@andresguisado thanks for your report! I'll try to investigate this issue.
