### ISSUE TITLE
Github action for reporgen script

### ISSUE THREAD

**Issue by rcarpio-hbo** [aquasecurity/reportgen#29]
Hi! I have created a github-action for this script:
https://github.com/rcarpio-hbo/aqua-reportgen-action 

Welcome feedback is welcome!

**Comment by jerbia** [comment]
Thanks @rcarpio-hbo. This is very cool!

If it's OK with you, I would like to add a reference to this project from the readme.md.
Can you submit a pull request for that? Probably add a section about Community Integrations to the readme, with reference to the Github Action.

**Comment by rcarpio-hbo** [comment]
yes, I will do it!
