### ISSUE TITLE
Add support to show only high/critical vulnerabilities

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/reportgen#3]
Add "-severity=critical/high/medium/low" to only get these vulnerabilities.
It should be possible to provide multiple criteria (e.g. critical and high).

To implement this, you need to add "&severity=high" to the /vulnerability REST API request.
Note that you can only filter by one severity, so in order to get both critical and high you need to call the REST API twice (once with severity high, second with severity critical).

**Comment by afdesk** [comment]
@jerbia Is 'severity' a required param?
if no, what is a default value?

**Comment by jerbia** [comment]
It's not required. If not specified you should export all vulnerabilities.

**Comment by afdesk** [comment]
@jerbia Should it show all vulnerabilities for all pages? or only for first page (as now)?

**Comment by jerbia** [comment]
@afdesk First page should always show all vulnerabilities.

**Comment by afdesk** [comment]
@jerbia this issue is ready for testing. pushed.

**Comment by jerbia** [comment]
@afdesk  It does not work.
When I add "-severity critical" to the command line, it seems that there is an infinite loop 
Getting data from <server>/api/v2/images/Docker Hub/nginx/latest/vulnerabilities?pagesize=100&page=2&severity=critical
Getting data from <server>/api/v2/images/Docker Hub/nginx/latest/vulnerabilities?pagesize=100&page=3&severity=critical
Getting data from <server>/api/v2/images/Docker Hub/nginx/latest/vulnerabilities?pagesize=100&page=4&severity=critical

I tried scanning the "nginx:latest" image from Docker Hub registry.

**Comment by afdesk** [comment]
@jerbia did you add the server?

**Comment by afdesk** [comment]
> 
> 
> @afdesk It does not work.
> When I add "-severity critical" to the command line, it seems that there is an infinite loop
> Getting data from /api/v2/images/Docker Hub/nginx/latest/vulnerabilities?pagesize=100&page=2&severity=critical
> Getting data from /api/v2/images/Docker Hub/nginx/latest/vulnerabilities?pagesize=100&page=3&severity=critical
> Getting data from /api/v2/images/Docker Hub/nginx/latest/vulnerabilities?pagesize=100&page=4&severity=critical
> 
> I tried scanning the "nginx:latest" image from Docker Hub registry.

very strange
my results: 

`Next severities will be selected:`
`* high`
`Getting data from https://demolab.aquasec.com/api/v2/images/Docker Hub/nginx/latest/malware`
`Getting data from https://demolab.aquasec.com/api/v2/images/Docker Hub/nginx/latest`
`Getting data from https://demolab.aquasec.com/api/v2/images/Docker Hub/nginx/latest/sensitive`
`Getting data from https://demolab.aquasec.com/api/v2/images/Docker Hub/nginx/latest/vulnerabilities?pagesize=100&page=1&severity=high`
`[DEBUG] Number of vulnerabilities: 4`
`Report was written to report.pdf`

**Comment by jerbia** [comment]
i doubled checked - same behaviour (infinite loop). If I don't provide the "-severity" parameter then it works OK.

Can you send me your command line (mask the user and password)

**Comment by afdesk** [comment]
@jerbia 
`docker run --rm --env-file .env -it report -registry "Docker Hub" -image "nginx:latest" -severity high`

**Comment by afdesk** [comment]
@jerbia my .env file:
`server=https://demolab.aquasec.com/`
`user=****`
`password=****`

**Comment by afdesk** [comment]
@jerbia I reproduced this issue. will fix

**Comment by afdesk** [comment]
fixed. pushed

**Comment by jerbia** [comment]
Thanks, the bug is fixed.

Running this I think we will need to do a small change to make it more usable:

Can you change the behaviour of severity, to include get all severities in a comma seperated list insetad of providing the "-severity" multiple times? 

I think it will be more usable this way.

So for example, if I want to get both critical and high I will specify:
"-severity critical,high"

**Comment by afdesk** [comment]
@jerbia I saw strange behavior for `"ashex/pokemongo-map:latest"`:

I run next command: `-registry "Docker Hub" -image "ashex/pokemongo-map/latest" -severity high`
and CLI receives `80` vulnerabilities, but generar response tells about `81` high level vulnerabilities.

How I can test it?

**Comment by afdesk** [comment]
> Running this I think we will need to do a small change to make it more usable:
> Can you change the behaviour of severity, to include get all severities in a comma seperated list insetad of providing the "-severity" multiple times?
> I think it will be more usable this way.
> So for example, if I want to get both critical and high I will specify:
> "-severity critical,high"

@jerbia ok. I can change it.

**Comment by afdesk** [comment]
@jerbia behavor of severity param was changed. pushed.

**Comment by jerbia** [comment]
Works.
