### ISSUE TITLE
Add information about previous scans

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/reportgen#4]
We would like to add a section about previous scans that will be like this:

![image](https://user-images.githubusercontent.com/3126261/79778023-c6856d00-8340-11ea-9bde-ae1ac7a058f6.png)

(no need to show the small icon of the bug).

This information should be displayed in the PDF before the details vulnerability results (right after the malware information).

It should have a title of "Scan History" with font size 12.

You can get the scan history from this API:

/api/v2/images/Docker%20Hub/jerbi/orders-apache/1.0/scan_history?order_by=-date&registry=Docker+Hub&repo=jerbi%2Forders-apache&tag=1.0&page=1&page_size=10

**Comment by afdesk** [comment]
@jerbia 
I added a scan history block in `issue-4` branch
Can you review it? I need feedback
if all right, I'll create pull request

**Comment by jerbia** [comment]
It looks OK. It's not very clear that the last item in the scan history issues is the number of malwares.
Would it be possible to add the small "bug" sign near it, like we have in the html design?

![image](https://user-images.githubusercontent.com/3126261/80236654-15464600-8664-11ea-81e0-fe809bb0c355.png)

**Comment by afdesk** [comment]
@jerbia 
yes, i'll try to add this image.

**Comment by afdesk** [comment]
@jerbia added a spider icons to malwares. pushed. pull request was created too.

**Comment by jerbia** [comment]
works
