### ISSUE TITLE
Some vulnerabilities are showing empty resource name

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/reportgen#5]
See screenshot
![image](https://user-images.githubusercontent.com/3126261/79893164-52b09680-840c-11ea-8334-f3a8124efb0d.png)

The reason is that REST API response for /vulnerabilities will sometime have a resource without a name, just with a path property.
In this case you should take the "path" property. See below example of the "resource" property of a vulnerability result. As you can see, the name is empty, but the "path" has value. In that case use the path as the name field in the vulnerability table.

"resource":{
"type": "file",
"format": "",
"path": "/usr/local/tomcat/webapps/struts2-showcase.war:WEB-INF/lib/commons-collections-3.1.jar",
"name": "",
"version": "",
"arch": "",
"cpe": "file:/40fb048097caeacdb11dbb33b5755854d89efdeb",
"licenses": null,
"hash": "sha1:40fb048097caeacdb11dbb33b5755854d89efdeb"
},

**Comment by afdesk** [comment]
@jerbia this issue is ready for testing too. pushed.

**Comment by jerbia** [comment]
Thanks. I checked it and it is fixed.
